#!/usr/bin/python

import sys
import os
import os.path

yubi_vendor='1050'
devdir = '/sys/bus/usb/devices'
drvdir = '/sys/bus/usb/drivers/usb'


def get_devices():
    devices = []
    for dev in os.listdir(devdir):
        fn = '%s/%s/idVendor' % (devdir, dev)
        if not os.path.exists(fn):
            continue
        vendor = open(fn).read().strip()
        if vendor != yubi_vendor:
            continue
        print "Yubico device: %s" % dev
        devices.append(dev)
    return devices


def set_device(dev, mode):
    if mode == "on":
        control = "%s/bind" % drvdir
        if os.path.exists("%s/%s" % (drvdir, dev)):
            print "Device %s already bound" % dev
            return
    elif mode == "off":
        control = "%s/unbind" % drvdir
        if not os.path.exists("%s/%s" % (drvdir, dev)):
            print "Device %s not bound" % dev
            return
    print "%s > %s" % (dev, control)
    with open(control, 'w') as fo:
        fo.write(dev)


def main():
    devices = get_devices()

    mode = sys.argv[1]
    if mode not in ['on', 'off']:
        print "Please indicate 'on' or 'off'"
        sys.exit(1)

    for dev in devices:
        set_device(dev, mode)


if __name__ == '__main__':
    main()
