#!/usr/bin/python

import sys
import os

yubi_vendor='1050'
#yubi_product='0010'
devdir = '/sys/bus/usb/devices'
devices = []
for dev in os.listdir(devdir):
    fn = '%s/%s/idVendor' % (devdir, dev)
    if not os.path.exists(fn):
        continue
    vendor = open(fn).read().strip()
    if vendor != yubi_vendor:
        continue
    print "Yubico device: %s" % dev
    devices.append(dev)

if sys.argv[1] == "on":
    control = "/sys/bus/usb/drivers/usb/bind"
elif sys.argv[1] == "off":
    control = "/sys/bus/usb/drivers/usb/unbind"
else:
    print "Please indicate 'on' or 'off'"
    sys.exit(1)

for dev in devices:
    print "%s > %s" % (dev, control)
    with open(control, 'w') as fo:
        fo.write(dev)
